{
 "title": "GENERAL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "klover",
     "rawSql": "SELECT creation_date, CAST(CONV(HEX(SUBSTRING(datagram, 34, 1)), 16, 10) AS INT)  \nas STATE FROM klover.stove_log \nORDER BY creation_date DESC\nLIMIT 1440;\n"
    }
   ]
  },
  {
   "title": "Power",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Level" } },
   "targets": [
    {
     "dataset": "klover",
     "rawSql": "SELECT creation_date, CAST(CONV(HEX(SUBSTRING(datagram, 53, 1)), 16, 10) AS INT)  \nas Level FROM klover.stove_log \nORDER BY creation_date DESC\nLIMIT 1440;\n"
    }
   ]
  },
  {
   "title": "Water temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "klover",
     "rawSql": "SELECT creation_date, CAST(CONV(HEX(SUBSTRING(datagram, 4, 1)), 16, 10) AS INT)  \nas C° FROM klover.stove_log \nORDER BY creation_date DESC\nLIMIT 1440;\n\n"
    }
   ]
  },
  {
   "title": "Fumes Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "klover",
     "rawSql": "SELECT creation_date, \nCAST(\nCONV(CONCAT(HEX(SUBSTRING(datagram, 92, 1)), HEX(SUBSTRING(datagram, 91, 1))), 16, 10)  \nas INT)\nas C° \n\nFROM klover.stove_log \nORDER BY creation_date DESC LIMIT 1440;\n"
    }
   ]
  },
  {
   "title": "Water temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "klover",
     "rawSql": "SELECT creation_date, CAST(CONV(HEX(SUBSTRING(datagram, 4, 1)), 16, 10) AS INT)  \nas C° FROM klover.stove_log \nORDER BY creation_date DESC\nLIMIT 1;\n\n"
    }
   ]
  },
  {
   "title": "Fumes Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "klover",
     "rawSql": "SELECT creation_date, \nCAST(\nCONV(CONCAT(HEX(SUBSTRING(datagram, 92, 1)), HEX(SUBSTRING(datagram, 91, 1))), 16, 10)  \nas INT)\nas C° \nFROM klover.stove_log \nORDER BY creation_date DESC LIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Rpm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "dataset": "klover",
     "rawSql": "SELECT creation_date,  \nCAST( CONV(CONCAT(HEX(SUBSTRING(datagram, 57, 1)), HEX(SUBSTRING(datagram, 56, 1))), 16, 10)   as INT)*10 \nas Rpm  FROM klover.stove_log  \nORDER BY creation_date DESC LIMIT 1440;"
    }
   ]
  },
  {
   "title": "Amb Temp & Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "dataset": "klover",
     "rawSql": "SELECT creation_date,\n    POW(-1, ORD(SUBSTRING(datagram, 250, 1)) >> 7) * -- Calcola il segno\n    POW(2, ((ORD(SUBSTRING(datagram, 250, 1)) & 0x7F) << 1 | (ORD(SUBSTRING(datagram, 249, 1)) >> 7)) - 127) * -- Calcola l'esponente\n    (1 + -- Calcola la mantissa\n        ((ORD(SUBSTRING(datagram, 249, 1)) & 0x7F) / 128.0) +\n        (ORD(SUBSTRING(datagram, 248, 1)) / 256.0 / 128.0) +\n        (ORD(SUBSTRING(datagram, 247, 1)) / 256.0 / 256.0 / 128.0)\n    ) AS amb_temperature,\n    POW(-1, ORD(SUBSTRING(datagram, 254, 1)) >> 7) * -- Calcola il segno\n    POW(2, ((ORD(SUBSTRING(datagram, 254, 1)) & 0x7F) << 1 | (ORD(SUBSTRING(datagram, 253, 1)) >> 7)) - 127) * -- Calcola l'esponente\n    (1 + -- Calcola la mantissa\n        ((ORD(SUBSTRING(datagram, 253, 1)) & 0x7F) / 128.0) +\n        (ORD(SUBSTRING(datagram, 252, 1)) / 256.0 / 128.0) +\n        (ORD(SUBSTRING(datagram, 251, 1)) / 256.0 / 256.0 / 128.0)\n    ) AS amb_humidity\n\n\nFROM klover.stove_log\norder by creation_date desc limit 1440;"
    }
   ]
  }
 ]
}